(() => {
  'use strict';
  const $ = (s,r=document) => r.querySelector(s);
  const $$ = (s,r=document) => [...r.querySelectorAll(s)];
  const arrow = '<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14"/></svg>';
  const right = '<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M4 12h16M14 6l6 6-6 6"/></svg>';
  const img = (key,alt='',cls='') => `<img src="${ASSETS[key]}" alt="${alt}" class="${cls}" draggable="false">`;
  const projects = [
    {key:'kp',name:'KhiladiPro',short:'KhiladiPro',sector:'Sports / Computer vision',year:'2024–25',role:'Sole product designer',scope:'Web · Android · iOS',proof:'Shipped. Then invited back.',title:'A sports olympiad, through a phone camera.',decision:'A player is standing across the room. The score has to reach them.',body:'Registration, camera onboarding, drills and scoring for a paid sports olympiad. I took the experience from early flows to shipped screens in roughly eight weeks, then returned for an IPL campaign.',url:'projects/khiladipro-redesign-claude.html',images:['kpHome','kpStage','kpDrill','kpWin'],accent:'#ef6a43',label:'Play, from anywhere.'},
    {key:'ceda',name:'CEDA',short:'CEDA',sector:'Data / Research',year:'2023–24',role:'Sole product designer',scope:'Data workspace · Comparison · Sharing',proof:'A returning client at Ashoka University.',title:'From a question to a chart worth sharing.',decision:'Keep the data in view while people change the question.',body:'The Socio-Economic Data Portal for CEDA at Ashoka University. A workspace for exploring, comparing and sharing public data, following earlier work on their Ecometer and Agrimarket dashboards.',url:'projects/sedp-redesign-claude.html',images:['cedaBar','cedaCompare','cedaAgri'],accent:'#bda9f0',label:'A clearer view of the data.'},
    {key:'gm',name:'Getmega',short:'Getmega',sector:'Gaming / Core product',year:'2019–21',role:'In-house product designer',scope:'Core game flows · Contest states',proof:'Two years. Two business-model pivots.',title:'Making the next game feel obvious.',decision:'One contest card has thirteen things to say, without changing shape.',body:'Two years designing core game flows and their surrounding states, as Getmega moved through two business-model pivots. I joined as the second product designer; the design team grew to ten.',url:'projects/getmega-redesign-claude.html',images:['gmGame','gmLobby','gmLeaderboard','gmStates'],accent:'#b8dba5',label:'The next move, made clear.'},
    {key:'mp',name:'Mega Poker',short:'Mega Poker',sector:'Money / Transactions',year:'2024',role:'Sole product designer',scope:'Deposits · Withdrawals · Transfers',proof:'Brought in by Getmega’s former growth head.',title:'Money flows that leave less to interpretation.',decision:'The money you move and the bonus you earn deserve their own rows.',body:'Wallet flows, deposits, withdrawals and tournament discovery within an existing product. Making inherited money rules readable, while keeping the visual language familiar to returning players.',url:'projects/mega-poker-redesign-claude.html',images:['mpWallet','mpDeposit','mpWithdraw'],accent:'#d8c3ac',label:'Clarity, where it counts.'}
  ];
  const meta = [
    {name:'Selected',id:'selected',tag:'A designer, through the work.',tone:'Exacting / direct / quietly tactile',intro:'A tightly edited wall of work with a personal column alongside it. This direction spends most of the first screen on the products, with enough context to understand your level and scope.',layout:'A compact, persistent introduction beside a deliberately uneven gallery. Large product compositions carry the page. Roles and project scope are readable before a case study is opened.',interaction:'The gallery responds to the pointer with subtle depth. Switch CEDA between exploration and comparison, change the featured KhiladiPro screen, and inspect the work in a large preview.',craft:'System typography, a near-white ground, soft squared media panels and strong product colours. Larger images and deliberate cropping replace decorative interface chrome.'},
    {name:'Cinema',id:'cinema',tag:'Give the work the whole room.',tone:'Immersive / precise / atmospheric',intro:'A film-like presentation where one project fills the stage, while the entire collection remains one click away. It is designed around the scale of the work.',layout:'A short introduction, one large product stage, and a persistent four-project rail. The selected project’s role and scope stay visible next to the case-study link.',interaction:'Select a project or use the stage arrows to move through the collection. Screens shift with the pointer. An annotation reveals the product decision behind the image.',craft:'Almost-black, warm white, cinematic crop and a controlled pool of light. A large project name supplies hierarchy; small labels stay readable and restrained.'},
    {name:'Typographic',id:'typographic',tag:'A portfolio with a point of view.',tone:'Graphic / decisive / editorial',intro:'A type-led work index with a large, responsive preview. The project names become the page’s visual identity, making the work exceptionally easy to find.',layout:'Personal context occupies a short header. Four large project names form the main navigation, with a fixed visual preview alongside them. Each row also has a direct case-study link.',interaction:'Hover, focus, or select a project name to change the preview. The selected row develops a little motion and colour; the preview follows the pointer gently.',craft:'White, black and one electric blue. Large Archivo lettering with a compact rhythm. Square edges, few surfaces and generous margins make the hierarchy explicit.'},
    {name:'Spatial',id:'spatial',tag:'A working surface you can touch.',tone:'Physical / playful / carefully composed',intro:'A tactile studio surface with real product artifacts you can move. Personal context and role evidence anchor the composition so the play has a purpose.',layout:'A short introduction sits among a browser workspace, app screens and a game-flow study. A permanent project rail provides direct, predictable routes to the case studies.',interaction:'Drag an artifact by its handle, bring it to the front, adjust the depth, or restore the arrangement. Keyboard users can select a project from the rail. Mobile gets a compact, bounded composition.',craft:'Porcelain grey, convincing layered shadows, translucent controls and restrained blue. The objects move; the page around them stays steady.'},
    {name:'Colour Field',id:'colour',tag:'Four products. One unmistakable impression.',tone:'Expressive / expansive / assured',intro:'Four architectural colour fields form an interactive exhibition of the work. Every project is visible immediately, with the selected one opening into a larger composition.',layout:'A short identity line above a full-width accordion of projects. Each field has a title, role, real product imagery and a direct case-study link. The page ends in a compact experience and contact section.',interaction:'Hover, focus or select a project to open its field. The neighbouring projects remain visible. On a phone, a project selector opens one generous preview at a time.',craft:'Coral, pale lime, lavender and cool grey, with black type and very little framing. The large blocks of colour function as the layout itself.'},
    {name:'Frequency',id:'frequency',tag:'A little rhythm. A lot of work.',tone:'Personal / kinetic / considered',intro:'A more distinctive evolution of the playable name idea. A single-line kinetic signature gives the page character, while a large filmstrip of work starts immediately underneath it.',layout:'Name, a two-line introduction, then an expansive horizontal gallery. A Gallery / Index switch gives visitors a choice between visual exploration and a quick reading path.',interaction:'Move across the name to create a wave; optional sound turns it into an instrument. Drag the project strip or use its arrows. Switch to Index for a compact overview of roles and scope.',craft:'Warm white, deep ink and a sharp persimmon accent. Wide Mona Sans lettering, large image crops and a single responsive line supply a distinctive identity.'}
  ];
  const status = (text='Open to senior roles, founding teams & projects') => `<span class="availability"><i></i>${text}</span>`;
  const caseLink = (p,label='Case study',cls='case-link') => `<a class="${cls}" href="${p.url}" aria-label="${label}: ${p.name}" target="_blank" rel="noopener">${label}${arrow}</a>`;
  const inspect = (p,label='Look closer') => `<button class="inspect" data-inspect="${p.key}" aria-label="${label}: ${p.name}">${label}${arrow}</button>`;
  const nav = (n,extra='') => `<header class="site-header"><a class="brand" href="#${meta[n].id}" aria-label="Priyank Agarwal home"><span class="brand-glyph" aria-hidden="true">p<span>a</span></span><span>Priyank Agarwal</span></a><span class="nav-caption">Independent product designer</span><nav aria-label="${meta[n].name} navigation"><a href="#work-${n}">Work</a><a href="about-redesign-claude.html" target="_blank" rel="noopener">About</a>${extra}<a class="contact-link" href="mailto:hello@priyank.design">Let’s talk ${arrow}</a></nav></header>`;
  const art = (p,variant='') => {
    let content;
    if(p.key==='kp') content=`<div class="track-lines" aria-hidden="true"><i></i><i></i><i></i><i></i></div><span class="art-word" aria-hidden="true">PLAY.</span>${img('kpStage','KhiladiPro stage selection interface','device device-back')}${img('kpHome','KhiladiPro home screen','device device-front')}<span class="art-seal" aria-hidden="true">Made to <br>move you. <b>↗</b></span>`;
    if(p.key==='ceda') content=`<span class="data-orbit" aria-hidden="true"></span><span class="art-word" aria-hidden="true">See more.</span><div class="browser-object"><div class="browser-chrome"><span class="browser-dots"><i></i><i></i><i></i></span><span>Socio-Economic Data Portal</span><span>↗</span></div>${img('cedaCompare','CEDA workspace comparing two data maps','browser-image')}</div><div class="data-chip" aria-hidden="true"><span class="mini-bars"><i></i><i></i><i></i><i></i><i></i></span>Explore. Compare. Share.</div>`;
    if(p.key==='gm') content=`<span class="game-orbit" aria-hidden="true"></span><div class="playing-card playing-card-one" aria-hidden="true"><span>A <br>♠</span><b>♠</b><span>A</span></div><div class="playing-card playing-card-two" aria-hidden="true"><span>A <br>♣</span><b>♣</b><span>A</span></div>${img('gmGame','Getmega game interface','device device-front')}${img('gmLeaderboard','Getmega contest leaderboard','device device-back')}<span class="art-seal" aria-hidden="true">Every state <br>in play. <b>↗</b></span>`;
    if(p.key==='mp') content=`<span class="wallet-orbit" aria-hidden="true"></span><span class="art-word" aria-hidden="true">₹</span>${img('mpDeposit','Mega Poker deposit interface','device device-back')}${img('mpWallet','Mega Poker wallet interface','device device-front')}<span class="money-chip" aria-hidden="true"><span>Principal</span><i>+</i><span>Bonus</span></span>`;
    return `<div class="art art-${p.key} ${variant}" data-parallax>${content}</div>`;
  };
  const proof = n => `<section class="proof-band"><p>Trusted with the <br><strong>complicated parts.</strong></p><div><strong>IIT Guwahati</strong><span>Bachelor of Design</span></div><div><strong>Getmega</strong><span>Two years in-house</span></div><div><strong>2 of 3</strong><span>Freelance clients returned</span></div><a href="about-redesign-claude.html" target="_blank" rel="noopener">The full story ${arrow}</a></section>`;
  const ending = n => `<section class="closing"><div><p class="kicker">A team, a new product, a good problem.</p><h2>Let’s make it <br>worth using.</h2><a class="email-link" href="mailto:hello@priyank.design">hello@priyank.design ${arrow}</a></div><div class="closing-aside"><p>Senior product design for products with real complexity. Available for full-time roles, founding teams and independent work.</p><div class="closing-links"><a href="about-redesign-claude.html" target="_blank" rel="noopener">About ${arrow}</a><a href="https://www.linkedin.com/in/priyank1205/" target="_blank" rel="noopener">LinkedIn ${arrow}</a><a href="https://drive.google.com/file/d/0B0y_QT-8mXwgRFhmWEdUWkpKOHc/view?usp=sharing&amp;resourcekey=0-Q4joErTGFsTqmVHZnpbYYw" target="_blank" rel="noopener">Résumé ${arrow}</a></div></div></section><footer class="site-footer"><span>© 2026 Priyank Agarwal</span><span>Bengaluru · <span data-clock>IST</span></span><button data-top>Back to top ↑</button></footer>`;
  const selectedCard = (p,i) => `<article class="selected-card sc-${p.key}"><header><div><h2>${p.name}</h2><p>${p.role}</p></div><span>${p.year}</span></header>${art(p)}<div class="card-options">${p.key==='ceda'?'<div class="segmented" role="group" aria-label="CEDA preview"><button class="active" data-ceda-view="cedaCompare" aria-pressed="true">Compare</button><button data-ceda-view="cedaBar" aria-pressed="false">Explore</button></div>':p.key==='kp'?'<button class="screen-cycle" data-kp-cycle>Next screen <span>↻</span></button>':p.key==='gm'?'<button class="screen-cycle" data-deal>Shuffle <span>↻</span></button>':''}${inspect(p,'Inspect')}</div><footer><p>${p.label}</p>${caseLink(p)}</footer></article>`;
  const selected = `<section class="direction selected" id="selected" role="tabpanel" aria-labelledby="direction-tab-0"><div class="selected-layout"><aside class="personal-column"><div><a class="personal-avatar" href="about-redesign-claude.html" target="_blank" rel="noopener">${img('portrait','Priyank Agarwal')}<span class="avatar-orbit" aria-hidden="true">✳</span></a><h1>Priyank Agarwal</h1><p class="personal-role">Senior product designer</p><p class="personal-intro">I work on the parts <br>of a product people <br>need to <span>trust.</span></p><p class="personal-context">From core game flows to public data. <br>From the first sketch to what ships.</p><div class="personal-links"><a href="about-redesign-claude.html" target="_blank" rel="noopener">A little about me ${arrow}</a><a href="mailto:hello@priyank.design">Let’s work together ${arrow}</a></div></div><div class="personal-bottom">${status('Open to roles & projects')}<p>B.Des, IIT Guwahati <br>Previously Getmega · Now independent</p><span>Bengaluru / <span data-clock>IST</span></span></div></aside><div class="selected-main"><header class="collection-head"><span>Selected work</span><span>Product thinking, in the details.</span><span>01—04</span></header><div class="selected-grid" id="work-0">${projects.map(selectedCard).join('')}</div><div class="selected-note"><span>More curiosity, fewer tabs.</span><a href="projects/timestamped-summary.html" target="_blank" rel="noopener">A tool I designed and built for myself ${arrow}</a></div>${proof(0)}${ending(0)}</div></div></section>`;
  const cinema = `<section class="direction cinema" id="cinema" role="tabpanel" aria-labelledby="direction-tab-1" hidden><div class="wide-page">${nav(1)}<section class="cinema-intro"><h1>Product design. <br><span>Considered, all the way through.</span></h1><div><p>Priyank Agarwal · Senior product designer <br>Games, money, data. The decisions in between.</p>${status('Open for the next chapter')}</div></section><section class="cinema-stage" id="work-1" aria-label="Featured project" data-cinema-stage>${projects.map((p,i)=>`<article class="cinema-scene cinema-${p.key} ${i===1?'active':''}" data-cinema-scene="${i}" ${i!==1?'hidden':''}>${art(p,'cinema-art')}<div class="cinema-topline"><span>${p.sector}</span><span>${String(i+1).padStart(2,'0')} / 04</span></div><button class="annotation-trigger" data-annotation aria-expanded="false"><span>+</span> A design decision</button><div class="cinema-annotation" hidden><p>${p.decision}</p>${inspect(p,'Explore the details')}</div><footer class="cinema-caption"><div><p>${p.role} / ${p.year}</p><h2>${p.name}</h2></div><div><p>${p.label}</p>${caseLink(p,'View case study')}</div></footer></article>`).join('')}<div class="cinema-arrows"><button data-cinema-prev aria-label="Previous featured project">←</button><button data-cinema-next aria-label="Next featured project">→</button></div></section><nav class="film-navigation" aria-label="Featured projects">${projects.map((p,i)=>`<button data-cinema="${i}" class="${i===1?'active':''}" aria-pressed="${i===1}"><span class="film-number">0${i+1}</span><span>${p.name}<small>${p.sector}</small></span><span class="film-progress"></span></button>`).join('')}</nav>${proof(1)}${ending(1)}</div></section>`;
  const typographic = `<section class="direction typographic" id="typographic" role="tabpanel" aria-labelledby="direction-tab-2" hidden><div class="wide-page">${nav(2)}<header class="type-intro"><h1>Senior product designer. <br>Independent mind. Hands-on maker.</h1><div>${status('Available for roles & collaborations')}<span>B.Des, IIT Guwahati / Bengaluru</span></div></header><div class="type-layout" id="work-2"><div class="type-list"><div class="type-index-head"><span>Selected work</span><span>2019—2025</span></div>${projects.map((p,i)=>`<article class="type-row ${i===0?'active':''}" data-type-row="${i}"><button data-type-project="${i}" aria-pressed="${i===0}"><span class="row-number">0${i+1}</span><span class="type-name">${p.short}</span></button><a href="${p.url}" target="_blank" rel="noopener" aria-label="Read ${p.name} case study">${arrow}</a><p>${p.scope}</p></article>`).join('')}<p class="type-signoff">A few products. A lot of considered decisions.</p></div><div class="type-preview"><div class="type-preview-top"><span data-type-kind>${projects[0].sector}</span><span>Design preview</span></div><div class="type-preview-art">${art(projects[0])}</div><div class="type-preview-bottom"><p data-type-proof>${projects[0].proof}</p><button data-inspect="kp" data-type-inspect>Look closer ${arrow}</button></div><span class="type-crosshair" aria-hidden="true">+</span></div></div>${proof(2)}${ending(2)}</div></section>`;
  const spatial = `<section class="direction spatial" id="spatial" role="tabpanel" aria-labelledby="direction-tab-3" hidden><div class="wide-page">${nav(3)}<div class="spatial-canvas" id="work-3"><div class="spatial-bio"><p class="spatial-hello">Hello, I’m Priyank. <span aria-hidden="true">↘</span></p><h1>I make complex <br>products feel <br><span>thought through.</span></h1><p>A senior product designer working <br>across interfaces, systems, <br>and all the states in between.</p>${status('Open to good collaborations')}</div><div class="spatial-grid" aria-hidden="true"></div><article class="floating-object float-ceda" data-drag="ceda" data-project="ceda"><button class="drag-handle" aria-label="Select and drag CEDA preview"><span>CEDA / A workspace for public data</span><span aria-hidden="true">⠿</span></button>${img('cedaCompare','CEDA data comparison workspace')}<button class="object-inspect" data-inspect="ceda" aria-label="Inspect CEDA">${arrow}</button></article><article class="floating-object float-kp" data-drag="kp" data-project="kp"><button class="drag-handle" aria-label="Select and drag KhiladiPro preview"><span>KhiladiPro</span><span aria-hidden="true">⠿</span></button>${img('kpStage','KhiladiPro mobile stage details')}<button class="object-inspect" data-inspect="kp" aria-label="Inspect KhiladiPro">${arrow}</button></article><article class="floating-object float-mp" data-drag="mp" data-project="mp"><button class="drag-handle" aria-label="Select and drag Mega Poker preview"><span>Mega Poker</span><span aria-hidden="true">⠿</span></button>${img('mpWallet','Mega Poker mobile wallet')}<button class="object-inspect" data-inspect="mp" aria-label="Inspect Mega Poker">${arrow}</button></article><article class="floating-object float-gm" data-drag="gm" data-project="gm"><button class="drag-handle" aria-label="Select and drag Getmega preview"><span>Getmega / A system of states</span><span aria-hidden="true">⠿</span></button>${img('gmStates','Getmega contest card state system')}<button class="object-inspect" data-inspect="gm" aria-label="Inspect Getmega">${arrow}</button></article><div class="spatial-toolbar"><span class="spatial-hint">A few things from my desk. Drag to explore.</span><label>Depth <input type="range" min="0" max="100" value="50" data-depth aria-label="Object depth"></label><button data-reset-spatial>Reset ↺</button></div></div><nav class="spatial-projects" aria-label="Projects on the desk">${projects.map((p,i)=>`<div><button data-bring="${p.key}"><i style="background:${p.accent}"></i>${p.name}</button>${caseLink(p,'Case study')}</div>`).join('')}</nav>${proof(3)}${ending(3)}</div></section>`;
  const colour = `<section class="direction colour" id="colour" role="tabpanel" aria-labelledby="direction-tab-4" hidden><div class="wide-page">${nav(4)}<header class="colour-intro"><h1>A little clarity <br>goes a long way.</h1><div><p>Priyank Agarwal. Senior product designer. <br>Making games, money and data easier to navigate.</p>${status('Open to roles & projects')}</div></header><section class="colour-fields" id="work-4" aria-label="Selected project exhibition">${projects.map((p,i)=>`<article class="colour-panel colour-${p.key} ${i===0?'active':''}" data-colour-panel="${i}"><button class="field-trigger" data-colour="${i}" aria-pressed="${i===0}"><span>0${i+1}</span><span>${p.name}</span><span>↗</span></button><div class="field-caption"><p>${p.sector}</p><h2>${p.name}</h2></div>${art(p,'field-art')}<div class="field-footer"><div><p>${p.role}</p><span>${p.scope}</span></div>${caseLink(p,'Case study')}</div></article>`).join('')}</section><p class="colour-under"><span>Four different contexts. The same care.</span><span>Select a field to explore.</span></p>${proof(4)}${ending(4)}</div></section>`;
  const frequency = `<section class="direction frequency" id="frequency" role="tabpanel" aria-labelledby="direction-tab-5" hidden><div class="wide-page"><header class="frequency-header"><span>Independent designer / Bengaluru</span><nav aria-label="Frequency navigation"><a href="about-redesign-claude.html" target="_blank" rel="noopener">About</a><button data-sound aria-pressed="false">Sound <span>off</span><i aria-hidden="true">♫</i></button><a href="mailto:hello@priyank.design">Get in touch ${arrow}</a></nav></header><div class="signature" data-signature><h1 aria-label="Priyank Agarwal">${[...'Priyank Agarwal'].map((letter,i)=>`<span class="letter ${letter===' '?'letter-space':''}" aria-hidden="true" data-letter="${i}">${letter===' '?'&nbsp;':letter}</span>`).join('')}</h1><svg class="signature-wave" viewBox="0 0 1200 35" preserveAspectRatio="none" aria-hidden="true"><path d="M0 18 Q300 18 600 18T1200 18" data-wave/></svg></div><div class="frequency-intro"><p>Senior product designer. Core flows, difficult states, <br>and the details that make them feel simple.</p>${status('Open to roles, founding teams & projects')}</div><section class="frequency-work" id="work-5"><header class="frequency-tools"><div class="view-switch" role="group" aria-label="Work presentation"><button data-work-view="gallery" class="active" aria-pressed="true">Gallery</button><button data-work-view="index" aria-pressed="false">Index</button></div><span class="filmstrip-hint">Selected work / Drag to browse</span><div class="filmstrip-arrows"><button data-strip-prev aria-label="Previous project">←</button><button data-strip-next aria-label="Next project">→</button></div></header><div class="project-strip" data-strip tabindex="0" aria-label="Selected projects. Use arrow keys or drag to browse.">${projects.map((p,i)=>`<article class="strip-card"><div class="strip-image">${art(p)}${inspect(p,'Explore')}</div><footer><div><h2>${p.name}</h2><p>${p.role} / ${p.year}</p></div>${caseLink(p,'View study')}</footer></article>`).join('')}</div><div class="frequency-index" hidden>${projects.map((p,i)=>`<a href="${p.url}" target="_blank" rel="noopener"><span>0${i+1}</span><h2>${p.name}</h2><p>${p.scope}</p><span>${p.year}</span>${arrow}</a>`).join('')}</div></section><div class="frequency-note"><p>Design with a little rhythm. <br>Work with a lot of intention.</p><a href="projects/timestamped-summary.html" target="_blank" rel="noopener">Also building: Timestamped Summary ${arrow}</a></div>${proof(5)}${ending(5)}</div></section>`;
  $('#directions').innerHTML = [selected,cinema,typographic,spatial,colour,frequency].join('');
  $('.review-tabs').innerHTML = meta.map((d,i)=>`<button id="direction-tab-${i}" role="tab" aria-selected="${i===0}" aria-controls="${d.id}" tabindex="${i===0?0:-1}" data-direction="${i}"><span>0${i+1}</span>${d.name}</button>`).join('');
  $('.overview-grid').innerHTML = meta.map((d,i)=>`<button class="overview-option ov-${d.id}" data-overview-choice="${i}"><span class="ov-art">${img('preview_'+d.id,`${d.name} homepage preview`,'ov-screen')}</span><span class="ov-label"><b>0${i+1} / ${d.name}</b>${arrow}</span><small>${d.tone}</small></button>`).join('');

  // Navigation and the review layer.
  let current = 0, cinemaIndex = 1, typeIndex = 0, colourIndex = 0;
  const reduced = matchMedia('(prefers-reduced-motion:reduce)');
  const fine = matchMedia('(hover:hover) and (pointer:fine)');
  let soundOn = false, audioContext, toastTimer, topLayer=6;
  const toast = text => { $('.toast').textContent=text; $('.toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('.toast').classList.remove('visible'),2400); };
  function choose(index,focus=false,hash=true){
    if(index<0||index>5)return;
    current=index;
    $$('.direction').forEach((el,n)=>{el.hidden=n!==index;el.classList.toggle('entered',n===index);});
    $$('[data-direction]').forEach((el,n)=>{el.setAttribute('aria-selected',String(n===index));el.tabIndex=n===index?0:-1;});
    $('.skip').href=`#work-${index}`;
    if(hash)try{history.replaceState(null,'',`#${meta[index].id}`);}catch{}
    document.title=`${meta[index].name} — Priyank Agarwal — New homepage directions`;
    $('[data-announcement]').textContent=`${meta[index].name} direction selected.`;
    window.scrollTo({top:0,behavior:'instant'});
    if(focus)$(`[data-direction="${index}"]`).focus({preventScroll:true});
  }
  $$('[data-direction]').forEach((b,i)=>{
    b.addEventListener('click',()=>choose(i));
    b.addEventListener('keydown',e=>{const next=e.key==='ArrowRight'?(i+1)%6:e.key==='ArrowLeft'?(i+5)%6:e.key==='Home'?0:e.key==='End'?5:null;if(next!==null){e.preventDefault();choose(next,true);}});
  });
  document.addEventListener('keydown',e=>{
    if($('dialog[open]')||e.ctrlKey||e.metaKey||e.altKey||e.target.closest('button,a,input,textarea,[contenteditable]'))return;
    if(/^[1-6]$/.test(e.key))choose(Number(e.key)-1);
  });
  $('[data-overview]').addEventListener('click',()=>$('.overview-dialog').showModal());
  $$('[data-overview-choice]').forEach(b=>b.addEventListener('click',()=>{$('.overview-dialog').close();choose(Number(b.dataset.overviewChoice));}));
  $$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
  $$('dialog').forEach(d=>d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close();}));
  $('[data-note]').addEventListener('click',()=>{
    const d=meta[current];$('#concept-title').textContent=d.name;$('[data-concept-number]').textContent=`Direction 0${current+1} / ${d.tone}`;
    $('.concept-content').innerHTML=`<p class="concept-lead">${d.intro}</p><div><h3>Structure</h3><p>${d.layout}</p></div><div><h3>Try it</h3><p>${d.interaction}</p></div><div><h3>Visual language</h3><p>${d.craft}</p></div><footer>Product imagery is from your existing work. Interactive previews are portfolio presentations, not live production interfaces.</footer>`;
    $('.concept-dialog').showModal();
  });
  $('[data-clean]').addEventListener('click',()=>{document.body.classList.add('clean-view');window.scrollTo({top:0,behavior:'instant'});});
  $('[data-return]').addEventListener('click',()=>{document.body.classList.remove('clean-view');window.scrollTo({top:0,behavior:'instant'});});
  $$('[data-top]').forEach(b=>b.addEventListener('click',()=>window.scrollTo({top:0,behavior:reduced.matches?'instant':'smooth'})));
  function openProject(key){
    const p=projects.find(p=>p.key===key);
    $('.project-content').innerHTML=`<div class="project-story"><p class="kicker">${p.sector} / ${p.year}</p><h2 id="project-title">${p.title}</h2><p class="project-lead">${p.body}</p><dl><div><dt>Role</dt><dd>${p.role}</dd></div><div><dt>Scope</dt><dd>${p.scope}</dd></div></dl><div class="decision"><span>A design decision</span><p>${p.decision}</p></div>${caseLink(p,'Read the full case study','project-primary')}</div><div class="project-artwork"><div class="project-image-stage ${p.key==='ceda'?'landscape':''}">${img(p.images[0],`${p.name} interface design`,'inspected-image')}</div><div class="project-image-controls" role="group" aria-label="${p.name} design screens">${p.images.map((key,i)=>`<button data-modal-image="${key}" aria-pressed="${i===0}" class="${i===0?'active':''}">${String(i+1).padStart(2,'0')}</button>`).join('')}<span>Original design screens</span></div></div>`;
    $$('[data-modal-image]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.modalImage;$('.inspected-image').src=ASSETS[key];$('.project-image-stage').classList.toggle('landscape',p.key==='ceda'||key==='gmStates');$$('[data-modal-image]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});}));
    $('.project-dialog').showModal();
  }
  document.addEventListener('click',e=>{const b=e.target.closest('[data-inspect]');if(b)openProject(b.dataset.inspect);});
  // Composed product imagery, not decorative tilt on the entire page.
  document.addEventListener('pointermove',e=>{
    if(!fine.matches||reduced.matches)return;
    const artEl=e.target.closest('[data-parallax]');if(!artEl)return;
    const r=artEl.getBoundingClientRect();
    artEl.style.setProperty('--mx',((e.clientX-r.left)/r.width-.5).toFixed(3));
    artEl.style.setProperty('--my',((e.clientY-r.top)/r.height-.5).toFixed(3));
  },{passive:true});
  document.addEventListener('pointerout',e=>{const a=e.target.closest('[data-parallax]');if(a&&!a.contains(e.relatedTarget)){a.style.setProperty('--mx',0);a.style.setProperty('--my',0);}});
  $$('[data-ceda-view]').forEach(b=>b.addEventListener('click',()=>{const c=b.closest('.selected-card');$('.browser-image',c).src=ASSETS[b.dataset.cedaView];$('.browser-image',c).alt=b.dataset.cedaView==='cedaBar'?'CEDA workspace exploring a bar chart':'CEDA workspace comparing two data maps';$$('[data-ceda-view]',c).forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});}));
  let kpScreen=0;
  $('[data-kp-cycle]').addEventListener('click',()=>{$('.sc-kp .device-back').src=ASSETS[projects[0].images[kpScreen]];$('.sc-kp .device-back').alt=$('.sc-kp .device-front').alt;kpScreen=(kpScreen+1)%4;$('.sc-kp .device-front').src=ASSETS[projects[0].images[kpScreen]];$('.sc-kp .device-front').alt=`KhiladiPro ${['home','stage','drill','completion'][kpScreen]} screen`;$('[data-announcement]').textContent=`KhiladiPro ${['home','stage','drill','completion'][kpScreen]} screen.`;});
  $('[data-deal]').addEventListener('click',()=>{$('.sc-gm').classList.toggle('dealt');note(4);});
  function setCinema(index){
    cinemaIndex=(index+4)%4;
    $$('[data-cinema-scene]').forEach((s,i)=>{s.hidden=i!==cinemaIndex;s.classList.toggle('active',i===cinemaIndex);s.classList.toggle('switched',i===cinemaIndex);});
    $$('[data-cinema]').forEach((b,i)=>{b.classList.toggle('active',i===cinemaIndex);b.setAttribute('aria-pressed',String(i===cinemaIndex));});
    $('[data-announcement]').textContent=`Featured project: ${projects[cinemaIndex].name}.`;
  }
  $$('[data-cinema]').forEach(b=>b.addEventListener('click',()=>setCinema(Number(b.dataset.cinema))));
  $('[data-cinema-prev]').addEventListener('click',()=>setCinema(cinemaIndex-1));
  $('[data-cinema-next]').addEventListener('click',()=>setCinema(cinemaIndex+1));
  $$('[data-annotation]').forEach(b=>b.addEventListener('click',()=>{const panel=b.nextElementSibling;panel.hidden=!panel.hidden;b.setAttribute('aria-expanded',String(!panel.hidden));$('span',b).textContent=panel.hidden?'+':'−';}));
  function setType(index){
    if(typeIndex===index)return;typeIndex=index;const p=projects[index];
    $$('[data-type-row]').forEach((row,i)=>row.classList.toggle('active',i===index));
    $$('[data-type-project]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));
    $('.type-preview-art').innerHTML=art(p);$('[data-type-kind]').textContent=p.sector;$('[data-type-proof]').textContent=p.proof;$('[data-type-inspect]').dataset.inspect=p.key;
  }
  $$('[data-type-project]').forEach(b=>{const run=()=>setType(Number(b.dataset.typeProject));b.addEventListener('click',()=>{run();if(matchMedia('(max-width:640px)').matches)$('.type-preview').scrollIntoView({block:'start',behavior:reduced.matches?'instant':'smooth'});});b.addEventListener('focus',run);b.addEventListener('pointerenter',()=>{if(fine.matches)run();});});
  // Bounded dragging: handles retain click/keyboard selection, art stays in reach.
  const dragItems=$$('[data-drag]');
  function bring(key){const el=$(`[data-drag="${key}"]`);el.style.zIndex=String(++topLayer);dragItems.forEach(x=>x.classList.toggle('chosen',x===el));$$('[data-bring]').forEach(x=>x.classList.toggle('active',x.dataset.bring===key));}
  dragItems.forEach(el=>{
    const handle=$('.drag-handle',el);let drag;
    handle.addEventListener('pointerdown',e=>{if(e.button!==0)return;bring(el.dataset.drag);const r=el.getBoundingClientRect(),canvas=$('.spatial-canvas').getBoundingClientRect();drag={x:e.clientX,y:e.clientY,dx:Number(el.dataset.dx||0),dy:Number(el.dataset.dy||0),left:r.left-canvas.left,top:r.top-canvas.top,width:r.width,height:r.height,cw:canvas.width,ch:canvas.height};handle.setPointerCapture(e.pointerId);el.classList.add('dragging');});
    handle.addEventListener('pointermove',e=>{if(!drag)return;const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));const dx=clamp(e.clientX-drag.x,-drag.left+8,drag.cw-drag.left-drag.width-8),dy=clamp(e.clientY-drag.y,-drag.top+8,drag.ch-drag.top-50);el.dataset.dx=String(drag.dx+dx);el.dataset.dy=String(drag.dy+dy);el.style.setProperty('--dx',`${drag.dx+dx}px`);el.style.setProperty('--dy',`${drag.dy+dy}px`);});
    const end=()=>{drag=null;el.classList.remove('dragging');};handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end);handle.addEventListener('lostpointercapture',end);handle.addEventListener('click',()=>bring(el.dataset.drag));
  });
  $$('[data-bring]').forEach(b=>b.addEventListener('click',()=>bring(b.dataset.bring)));
  $('[data-depth]').addEventListener('input',e=>{$('.spatial-canvas').style.setProperty('--depth',e.target.value);$('.spatial-canvas').style.setProperty('--shadow-y',`${8+e.target.value*.3}px`);$('.spatial-canvas').style.setProperty('--shadow-blur',`${16+e.target.value*.6}px`);});
  $('[data-reset-spatial]').addEventListener('click',()=>{dragItems.forEach(el=>{el.style.removeProperty('--dx');el.style.removeProperty('--dy');el.style.removeProperty('z-index');el.dataset.dx='0';el.dataset.dy='0';el.classList.remove('chosen');});$$('[data-bring]').forEach(b=>b.classList.remove('active'));$('[data-depth]').value=50;$('.spatial-canvas').style.removeProperty('--shadow-y');$('.spatial-canvas').style.removeProperty('--shadow-blur');toast('Back in place.');});
  function setColour(index){colourIndex=index;$$('[data-colour-panel]').forEach((panel,i)=>panel.classList.toggle('active',i===index));$$('[data-colour]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));}
  $$('[data-colour]').forEach(b=>{const run=()=>setColour(Number(b.dataset.colour));b.addEventListener('click',run);b.addEventListener('focus',run);b.closest('.colour-panel').addEventListener('pointerenter',()=>{if(fine.matches)run();});});
  // A kinetic signature and an optional, gesture-unlocked instrument.
  const notes=[293.66,329.63,369.99,440,493.88,587.33,659.25];let lastNote=0;
  function note(index){if(!soundOn||Date.now()-lastNote<60)return;lastNote=Date.now();try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain(),t=audioContext.currentTime;osc.type='sine';osc.frequency.value=notes[index%7];gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.065,t+.01);gain.gain.exponentialRampToValueAtTime(.0001,t+.55);osc.connect(gain);gain.connect(audioContext.destination);osc.start(t);osc.stop(t+.57);}catch{}}
  $('[data-sound]').addEventListener('click',e=>{soundOn=!soundOn;e.currentTarget.setAttribute('aria-pressed',String(soundOn));$('span',e.currentTarget).textContent=soundOn?'on':'off';if(soundOn)note(0);});
  const letters=$$('[data-letter]');
  letters.forEach((letter,i)=>{letter.addEventListener('pointerenter',()=>note(i));letter.addEventListener('pointerdown',()=>note(i));});
  $('[data-signature]').addEventListener('pointermove',e=>{if(reduced.matches)return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width;letters.forEach((letter,i)=>{const delta=(i/(letters.length-1))-x,weight=Math.exp(-delta*delta*70);letter.style.setProperty('--lift',`${-weight*13}px`);letter.style.setProperty('--angle',`${delta*weight*17}deg`);letter.style.setProperty('--stretch',String(1+weight*.11));});const pos=x*1200;$('[data-wave]').setAttribute('d',`M0 18 Q${Math.max(0,pos-200)} 18 ${Math.max(0,pos-90)} 18 Q${pos} -8 ${Math.min(1200,pos+90)} 18 T1200 18`);},{passive:true});
  $('[data-signature]').addEventListener('pointerleave',()=>{letters.forEach(l=>{l.style.setProperty('--lift','0px');l.style.setProperty('--angle','0deg');l.style.setProperty('--stretch','1');});$('[data-wave]').setAttribute('d','M0 18 Q300 18 600 18T1200 18');});
  const strip=$('[data-strip]');let stripDrag;
  strip.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button,a')||!fine.matches)return;stripDrag={x:e.clientX,left:strip.scrollLeft};strip.setPointerCapture(e.pointerId);strip.classList.add('dragging');});
  strip.addEventListener('pointermove',e=>{if(stripDrag)strip.scrollLeft=stripDrag.left-(e.clientX-stripDrag.x);});
  const stopStrip=()=>{stripDrag=null;strip.classList.remove('dragging');};strip.addEventListener('pointerup',stopStrip);strip.addEventListener('pointercancel',stopStrip);
  const moveStrip=dir=>strip.scrollBy({left:dir*($('.strip-card').offsetWidth+20),behavior:reduced.matches?'instant':'smooth'});
  $('[data-strip-prev]').addEventListener('click',()=>moveStrip(-1));$('[data-strip-next]').addEventListener('click',()=>moveStrip(1));
  strip.addEventListener('keydown',e=>{if(e.target!==strip)return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();moveStrip(e.key==='ArrowRight'?1:-1);}});
  $$('[data-work-view]').forEach(b=>b.addEventListener('click',()=>{const index=b.dataset.workView==='index';strip.hidden=index;$('.frequency-index').hidden=!index;$('.filmstrip-arrows').hidden=index;$('.filmstrip-hint').textContent=index?'Selected work / At a glance':'Selected work / Drag to browse';$$('[data-work-view]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});}));
  const clock=()=>{const text=new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'}).format(new Date());$$('[data-clock]').forEach(el=>el.textContent=`${text} IST`);};clock();setInterval(clock,60000);
  const start=meta.findIndex(d=>location.hash===`#${d.id}`);choose(start<0?0:start,false,false);if(!location.hash)$('.overview-dialog').showModal();
  addEventListener('hashchange',()=>{const n=meta.findIndex(d=>location.hash===`#${d.id}`);if(n>=0&&n!==current)choose(n,false,false);});
})();
